### ISSUE TITLE
Why did you use "sys.stdin.readline()"?

### ISSUE THREAD

**Issue by dowork0711** [hjun-park/Coding-test-self-study#1]
Thank you for teaching me every time.

Why does it get faster if you import "sys" and use the "stdin.readline()" method?

Why did you do NOT use normal input?

I'll be waiting for your reply.

---

```python
import sys

n = int(input())
array = []

for i in range(n):
    array.append(int(sys.stdin.readline().rstrip()))    # sys로 입력받아야 훨씬 빠름
    # array.append(int(input()))

array = sorted(array)

for i in array:
    print(i, end='\n')
```

**Comment by hjun-park** [comment]
결론적으로 말씀드리면 input()이 더 무겁습니다. 

동작방식에 차이가 있습니다. 
링크는 맨 윗 설명만 보시면 됩니다.

1) input() 동작방식 <[input 설명](https://docs.python.org/3/library/functions.html#input)>
`input() -> 개행문자 '\n' 제거 -> 문자열로 변환 -> return`

2) sys.stdin.readline() 동작방식 <[sys.stdin() 설명](https://docs.python.org/ko/3/library/sys.html#sys.stdin)>
`readline() -> 사용자 입력을 버퍼에 보관하여 필요 시마다 읽음`

<br />

input()의 경우 하나씩 읽어들여와서 그 끝에 \n을 제거하는 작업이 있습니다. 
거기에 하나씩 읽어들여오기 때문에 일정 양을 버퍼에 넣어놓고 필요시마다 읽어오는 readline 하고 성능차이는 조금 있다고 합니다. 

<br />

자바의 Scanner, Buffered 차이, C언어에서의 Cout, printf 차이로도 비교할 수 있을 것같습니다. 

일반적인 상황에서 눈에 띌 정도로 그렇게 성능차이가 있지 않지만 코테에서는 입력값 혹은 테스트케이스가 많기 때문에 사용합니다. 

매번 sys.stdin.readline을 붙여쓰기 힘드므로 저는 아래와 같이 input을 새로 정의해서 사용합니다.
```python
import sys

input = sys.stdin.readline

number = int(input().rstrip())
```

참고할 만한 링크 : [stack-overflow](https://stackoverflow.com/questions/22623528/sys-stdin-readline-and-input-which-one-is-faster-when-reading-lines-of-inpu)
관련 백준 문제 : [15552번: 빠른 A+B](https://www.acmicpc.net/problem/15552)

**Comment by dowork0711** [comment]
Thank you for your friendly reply!

You provided me with a reference that was easy for me to understand.

I understood better because you said it was similar to the difference between the `Buffered` and the `Scanner` of Java. 😅

I think it will be very helpful in solving algorithm problems with time limit.

Thank you. Have a great day!

p.s. It's getting cold, so be careful not to catch a cold! 😁
